#!/bin/sh -e

# env | sort

if [ -z "$GOPATH" ]; then
	echo "GOPATH is not set"
	exit 1
fi

mkdir -p "$GOPATH"
cd "$GOPATH/.."

open .
cat <<EOF > README.txt
To reset the go and gopls install:
1. Deactivate the GoBang extension
2. Remove the go folder in this directory
3. Activate the GoBang extension
EOF

if [ ! -x "$GOPATH/bin/go" ]; then
	echo "Installing go..."
	curl -sL https://golang.org/dl/go1.15.8.darwin-amd64.tar.gz | tar xzf -
fi
echo "Go is installed"
go version

if [ ! -x "$GOPATH/bin/gopls" ]; then
	echo "Installing gopls"
	GO111MODULE=on "$GOPATH/bin/go" get golang.org/x/tools/gopls@v0.6.6
fi
echo "gopls is installed"
gopls version
